version: "3.1"
services:
  db:
    image: postgres:14.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f /tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/todoapp-test
    environment:
      RAILS_ENV: development
    ports:
      - "8008:3000"
    depends_on:
    - db
